name: Build Android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # - name: Install Ionic
      #   run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      # - name: Build Ionic App
      #   run: ionic build

      # - name: Copy Android
      #   run: ionic capacitor copy android

      # - name: Build Android Dev APK
      #   run: ionic capacitor build android

      # - name: Build Android Release APK
      #   run: ionic capacitor build android --release --prod

      - name: Build
        run: npm run build

      - name: deploy web
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build

      - name: Make gradlew executable
        working-directory: ./android/
        run: chmod +x ./gradlew

      - name: Generate the Android App assembleDebug
        working-directory: ./android/
        run: ./gradlew assembleDebug

      # - name: Upload dev APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #   name: app-dev
      #   working-directory: .
      #   path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Deploy apk
        working-directory: .
        run: |
          cd android/app/build/outputs/apk/debug/
          git init
          git config --global user.email prakash@sutara.org
          git config --global user.name  bhanugummana
          git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/chimple/cuba.git
          git checkout -b apk
          git add app-debug.apk
          git commit -m "created apk"
          #git push --force secure-origin apk
          #git push --set-upstream origin gh-pages
          git push origin apk -f

      # - name: Build web
      #   run: |
      #     npm run build
      #     echo "REPO_NAME=${{ github.event.repository.name }}"

      #   env:
      #     FLOW: "/${{ github.event.repository.name }}/"

      # - name: Deploy web
      #   working-directory: .
      #   run: |
      #     cd dist
      #     rm chimple-lib/.git
      #     git init
      #     git config --global user.email prakash@sutara.org
      #     git config --global user.name  bhanugummana
      #     git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/chimple/cuba-test.git
      #     git checkout -b gh-pages
      #     git add --all
      #     git commit -m "Updated web"
      #     git push origin gh-pages -f

      # - name: Upload release bundle
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release
      #     path: apk/app.aab
