name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - name: Checkout source
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: true
      #     token: ${{ secrets.ACCESS_TOKEN }}

      # - name: Setup java
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: "17"

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x

      #   - name: Install app dependencies
      #     run: npm install

      # - name: Create Google Services JSON File and key.jks
      #   working-directory: ./android/app/
      #   env:
      #     GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      #     SHA_KEY: ${{ secrets.SHA_KEY }}
      #   run: |
      #     echo $GOOGLE_SERVICES_JSON | base64 -di > google-services.json
      #     echo $SHA_KEY | base64 -di > key.jks
      - name: Extract Tag Name
        run: |
          # Extract the tag name from GITHUB_REF using sed (Linux/Unix-based systems)
          TAG_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')

          # Get the first two characters from the tag name
          SHORT_TAG_NAME=${TAG_NAME:0:2}

          echo "Short Tag Name: ${SHORT_TAG_NAME}"


      - name: Build
        env:
          CI: false
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID}}
          REACT_APP_ALGOLIA_APP_ID: ${{ secrets.REACT_APP_ALGOLIA_APP_ID }}
          REACT_APP_ALGOLIA_API_KEY: ${{ secrets.REACT_APP_ALGOLIA_API_KEY }}
          REACT_APP_HOT_UPDATE_SERVER: ${{ secrets.RELEASE_HOT_UPDATE_SERVER }}v1/

        # run: npm run build
        run: |
          # echo hot update server ${REACT_APP_HOT_UPDATE_SERVER}v1/
          echo tag name ${{ github.ref }}
          echo new $SHORT_TAG_NAME

    # - uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "release.tar.gz,foo/*.txt"
    #     bodyFile: "body.md"
